---
# tasks file for Ansible_Repo_role_create_instance
---
- name: Create an EC2 instance
  hosts: localhost
  vars:
    aws_instance_count: 1
    aws_instance_type: "{{ aws_instance_type }}"
    aws_image_id: "{{ aws_ami_id }}"
    aws_key_name: "{{ aws_key_name }}"
    aws_security_group: "{{ aws_security_group }}"
    aws_subnet_id: "{{ aws_subnet_id }}"
    aws_tag_name: "{{ aws_tag_name }}"
    aws_instance_name: "{{ aws_instance_name }}"
    aws_instance_tags: "{{ aws_instance_tags }}"
  tasks:
    - name: Launch EC2 instances
      ec2:
        region: "{{ aws_region }}"
        count: "{{ aws_instance_count }}"
        instance_type: "{{ aws_instance_type }}"
        image_id: "{{ aws_image_id }}"
        key_name: "{{ aws_key_name }}"
        security_group: "{{ aws_security_group }}"
        subnet_id: "{{ aws_subnet_id }}"
        assign_public_ip: yes
        instance_tags: "{{ aws_instance_tags }}"
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        ansible_user: ec2-user
        ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/mykey.pem"
        ansible_python_interpreter: /usr/bin/python3

